// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
  app: {
    head: {
      meta: [
        { name: 'viewport', content: 'width=device-width, initial-scale=1, viewport-fit=cover' },
      ],
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'preload',
          as: 'style',
          href: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap',
          onload: "this.onload=null;this.rel='stylesheet'",
        },
      ],
    },
  },
  runtimeConfig: {
    mongoUri: process.env.MONGO_URI || '',
    redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
    siteUrl: process.env.SITE_URL || 'http://localhost:3000',
    adminKey: process.env.ADMIN_KEY || '',
    sessionSecret: process.env.SESSION_SECRET || '',
    adminUsername: process.env.ADMIN_USERNAME || '',
    adminEmail: process.env.ADMIN_EMAIL || '',
    adminPassword: process.env.ADMIN_PASSWORD || '',
    adminSubdomain: process.env.ADMIN_SUBDOMAIN || '',
    amazonAccessKey: process.env.AMAZON_ACCESS_KEY || '',
    amazonSecretKey: process.env.AMAZON_SECRET_KEY || '',
    amazonPartnerTag: process.env.AMAZON_PARTNER_TAG || '',
    amazonRegion: process.env.AMAZON_REGION || 'us-east-1',
    amazonMarketplace: process.env.AMAZON_MARKETPLACE || 'www.amazon.com',
    ebayClientId: process.env.EBAY_CLIENT_ID || '',
    ebayClientSecret: process.env.EBAY_CLIENT_SECRET || '',
    ebayCampaignId: process.env.EBAY_CAMPAIGN_ID || '',
    bestBuyApiKey: process.env.BESTBUY_API_KEY || '',
    bestBuyCjPublisherId: process.env.BESTBUY_CJ_PUBLISHER_ID || '',
    walmartImpactSid: process.env.WALMART_IMPACT_SID || '',
    walmartImpactAuth: process.env.WALMART_IMPACT_AUTH || '',
    walmartImpactCatalogId: process.env.WALMART_IMPACT_CATALOG_ID || '',
    public: {
      siteUrl: process.env.SITE_URL || 'http://localhost:3000',
      adminSubdomain: process.env.ADMIN_SUBDOMAIN || '',
    },
  },
  nitro: {
    preset: 'vercel',
    compressPublicAssets: true,
    experimental: { tasks: true },
    scheduledTasks: {
      '0 2 * * *': ['products:discover'],
      '0 */6 * * *': ['prices:update'],
    },
    devStorage: {
      cache: { driver: 'memory' },
    },
  },
  routeRules: {
    '/': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=600' } },
    '/shop': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=600' } },
    '/products/**': { headers: { 'cache-control': 's-maxage=3600, stale-while-revalidate=86400' } },
    '/category/**': { headers: { 'cache-control': 's-maxage=1800, stale-while-revalidate=3600' } },
    '/api/products': { headers: { 'cache-control': 's-maxage=60, stale-while-revalidate=300' } },
    '/api/products/**': { headers: { 'cache-control': 's-maxage=120, stale-while-revalidate=600' } },
    '/api/categories/**': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=3600' } },
    '/api/affiliate/**': { headers: { 'cache-control': 'no-store' } },
    '/best/**': { headers: { 'cache-control': 's-maxage=3600, stale-while-revalidate=86400' } },
    '/collections': { headers: { 'cache-control': 's-maxage=86400, stale-while-revalidate=604800' } },
    '/collections/**': { isr: 3600, headers: { 'cache-control': 's-maxage=3600, stale-while-revalidate=86400' } },
    '/api/collections/**': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=3600' } },
    '/api/search': { headers: { 'cache-control': 's-maxage=30, stale-while-revalidate=120' } },
    '/api/best/**': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=3600' } },
    '/api/click': { headers: { 'cache-control': 'no-store' } },
    '/api/recommendations': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=3600' } },
    '/api/trending': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=600' } },
    '/api/admin/**': { headers: { 'cache-control': 'no-store' } },
    '/admin/**': { ssr: false, headers: { 'X-Robots-Tag': 'noindex, nofollow' } },
    '/partner/**': { ssr: false, headers: { 'X-Robots-Tag': 'noindex, nofollow' } },
    '/api/auth/**': { headers: { 'cache-control': 'no-store' } },
    '/api/partner/**': { headers: { 'cache-control': 'no-store' } },
    '/search': { headers: { 'cache-control': 'no-store', 'X-Robots-Tag': 'noindex' } },
    '/sitemap.xml': { headers: { 'cache-control': 's-maxage=3600' } },
  },
})
