// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },
  modules: ['@nuxtjs/tailwindcss'],
  runtimeConfig: {
    mongoUri: process.env.MONGO_URI || '',
    redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
    siteUrl: process.env.SITE_URL || 'http://localhost:3000',
    adminKey: process.env.ADMIN_KEY || '',
    amazonAccessKey: process.env.AMAZON_ACCESS_KEY || '',
    amazonSecretKey: process.env.AMAZON_SECRET_KEY || '',
    amazonPartnerTag: process.env.AMAZON_PARTNER_TAG || '',
    amazonRegion: process.env.AMAZON_REGION || 'us-east-1',
    amazonMarketplace: process.env.AMAZON_MARKETPLACE || 'www.amazon.com',
    public: {
      siteUrl: process.env.SITE_URL || 'http://localhost:3000',
    },
  },
  nitro: {
    compressPublicAssets: true,
    experimental: { tasks: true },
    scheduledTasks: { '0 */6 * * *': ['prices:update'] },
  },
  routeRules: {
    '/': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=600' } },
    '/products/**': { headers: { 'cache-control': 's-maxage=3600, stale-while-revalidate=86400' } },
    '/category/**': { headers: { 'cache-control': 's-maxage=1800, stale-while-revalidate=3600' } },
    '/api/products': { headers: { 'cache-control': 's-maxage=60, stale-while-revalidate=300' } },
    '/api/products/**': { headers: { 'cache-control': 's-maxage=120, stale-while-revalidate=600' } },
    '/api/categories/**': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=3600' } },
    '/api/affiliate/**': { headers: { 'cache-control': 'no-store' } },
    '/best/**': { headers: { 'cache-control': 's-maxage=3600, stale-while-revalidate=86400' } },
    '/api/search': { headers: { 'cache-control': 's-maxage=30, stale-while-revalidate=120' } },
    '/api/best/**': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=3600' } },
    '/api/click': { headers: { 'cache-control': 'no-store' } },
    '/api/recommendations': { headers: { 'cache-control': 's-maxage=300, stale-while-revalidate=3600' } },
    '/api/admin/**': { headers: { 'cache-control': 'no-store' } },
    '/admin/**': { ssr: false, headers: { 'X-Robots-Tag': 'noindex, nofollow' } },
    '/search': { headers: { 'cache-control': 'no-store', 'X-Robots-Tag': 'noindex' } },
    '/sitemap.xml': { headers: { 'cache-control': 's-maxage=3600' } },
  },
})
